[package]
name = "MeiVM2TUI"
version = "0.1.0"
edition = "2024"

[dependencies]
meivm2 = { version = "0.1.0", path = "./MeiVM2" }
clap = { version = "4.5.38", features = ["derive"] }
log = "0.4.27"
ratatui = "0.29.0"
slog = "2.7.0"
slog-scope = "4.4.0"
slog-stdlog = "4.1.1"
slog-term = "2.9.1"
